AWSTemplateFormatVersion: 2010-09-09
Description: Create Transit Gateway VPC Attachments
# I used the following source as an example to learn from - Cudos to https://github.com/vaidys2020.
# https://github.com/aws-samples/aws-transit-gateway-and-scalable-security-solutions/blob/main/transit-gateway-attachment.yaml


Parameters:
  MyChosenTransitGateway:
    Description:  Please enter the transit gateway id
    Type:  String

  MyAccountName:
    Description:  Please enter the AWS account Name
      Type: String

  MyTargetVPC:
    Description: Select the Transit Gateway that you would like to attach to
    Type: AWS::EC2::VPC::Id
  
  MyTargetSubnets:
    Description: Select the Subnets you would like to target for attachment
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  MyTransitGatewayAttachmentId:
   Type: AWS::EC2::TransitGatewayAttachment
   Properties:
      TransitGatewayId:  !Ref MyChosenTransitGateway
      VpcId:  !Ref MyTargetVPC
      SubnetIds:  !Ref MyTargetSubnets
      Tags: 
      - Key:  Account
        Value: !Sub '${AWS::AccountId}'
      - Key:  Account Name
        Value:  !Ref MyAccountName
      - Key: Name
        Value: !Sub '${AccountName}${AWS::Region}TGW_vpc'
      - Key:  Resource
        Value: VPC
      - Key: Organization
        Value: !Ref MyOrganization

Outputs:
  OrginazationOutput:
    Description: Organization Id
    Value: !Ref MyOrganization
  AccountOutput:
   Description: Account Number
   Value:  !Sub '${AWS::AccountId}' 
  AccountNameOutput:
    Description:  Account Name
    Value:  !Ref MyAccountName
    VPCIdOutput: 
     Description: VPC Id
     Value: !Ref VPCId
  TGWOutput:
   Description: The Transit Gateway Id
   Value:  !Ref TargetTransitGatewayId
  TGWAttachmentOutput:
   Description: The Transit Gateway Id
   Value:  !Ref MyTransitGatewayAttachmentId