AWSTemplateFormatVersion: 2010-09-09
Description: Create a Transit Gateway

Parameters:
# this is where the value for the AWS Organization goes...cannot infer it - no variable for that.
  OrgId: 
    Type: String
    Description: Enter Organization Id (e.g. o-12345) if Organization sharing is enabled
# The AWS documentation suggests that AWS side local ASN's should be unique
  LocalASN:
    Description: Add a unique ASN for this transit gateway
    Type: Number
    Default: 64512
    MinValue: 64512
    MaxValue: 65534
    ConstraintDescription: Must be between between 64512 and 65534
# Our transit gateway name will be stored in all of the resources associated with it, in the tags
  TransitGatewayName:
    Type: String
    Default: Transit Gateway
# This conditional identifies if we intend to share the transit gateway as a resource via RAM
  ShareWithOrg: 
    Type: String
    Default: false
    Description: Enable sharing with all AWS Accounts in an AWS Organization
    AllowedValues: 
      - true
      - false
  OrganizationAccountId:
    Type:  String
    Description:  Please enter the number of the AWS Account that is the admin for the Organization

# For tagging all related resources
  ConnectToGlobalNetworkManager:
    Type: String
    Default: false
    Description: Do you have a Global Network Manager you want to share this with?
    AllowedValues: 
      - true
      - false

# For tagging all related resources
  Product:
    Description:  Please enter the product being created
    Type: String
    Default:  "Transitive multi-account network"

# Metadata is used to format the parameter entry screens
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Transit Gateway Details
        Parameters:
          - TransitGatewayName
          - Product
          - LocalASN
      - Label:
          default: (Optional) Enable sharing with an AWS Organization
        Parameters:
          - ShareWithOrg
          - OrgId
          - OrganizationAccountId
      - Label:
          default: (Optional) Enable registration with a Global Network Manager
        Parameters:
          - ConnectToGlobalNetworkManager
    ParameterLabels:
      TransitGatewayName:
        default: Transit Gateway Name
      ShareWithOrg:
        default: Enable Sharing within an Organization
      OrgId:
        default: AWS Organization Id
      OrganizationAccountId:
        default: Provide the Organization associated AWS Account ID

Conditions:
  EnableRAM: 
    !Equals
      - !Ref ShareWithOrg
      - true

  EnableGlobalNetworkManager:  
    !Equals 
      - !Ref ConnectToGlobalNetworkManager
      - true

Resources:
  MyTransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
     AmazonSideAsn: !Ref LocalASN
     AutoAcceptSharedAttachments: enable
     DefaultRouteTableAssociation: enable
     DefaultRouteTablePropagation: enable
     Description:  Auto creation of the Transit Gateway
     MulticastSupport: disable
     DnsSupport: enable
     VpnEcmpSupport: enable
     Tags: 
     - Key: "Region"
       Value: !Sub '${AWS::Region}'
     - Key:  "Account"
       Value: !Sub '${AWS::AccountId}'
     - Key: "Product"
       Value: !Ref Product
     - Key: Name
       Value: !Sub '${TransitGatewayName}_tgw'
 
  TransitGatewayShare:
    Type: "AWS::RAM::ResourceShare"
    DependsOn: MyTransitGateway
    Condition: EnableRAM
    Properties:
      AllowExternalPrincipals: false
      Name: TransitGatewayOrgShare
      Principals: 
        - !Sub 'arn:aws:organizations::${OrganizationAccountId}:organization/${OrgId}'
      ResourceArns: 
        - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${MyTransitGateway}'

  TransitGatewayDMZRouteDomainId:
    Type: "AWS::EC2::TransitGatewayRouteTable"
    Properties:
      TransitGatewayId: !Ref MyTransitGateway
      Tags:
        - Key: Name
          Value: DMZ Routing Domain

  TheGlobalNetworkManager:
    Type: AWS::NetworkManager::TransitGatewayRegistration
    DependsOn: MyTransitGateway
    Condition: EnableGlobalNetworkManager
    Properties: 
      GlobalNetworkId: !ImportValue TheGlobalNetworkManagerId
      TransitGatewayArn: !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${MyTransitGateway}'

Outputs:
  TransitGatewayId: 
    Description: 'TransitGateway Id'
    Value: !Ref MyTransitGateway

  TransitGatewayDMZRouteDomainId:
    Description: 'Transit Gateway DMZ Route Domain'
    Value: !Ref TransitGatewayDMZRouteDomainId
    Export:
      Name: !Sub '${AWS::Region}::${AWS::AccountId}-tmg-rt'