
Resources:
  CamsEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-03d5c68bab01f3496
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref AdminSecurityGroup
        - !Ref HTTPSecurityGroup

  # an elastic IP for our instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref CamsEC2

  # our EC2 security group
  AdminSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 72.199.186.31/32

  # our second EC2 security group
  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 72.199.186.31/32
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 72.199.186.31/32
