AWSTemplateFormatVersion: 2010-09-09
Description: VPC creation to include one private subnet and one private ec2 instance t3.micro of the most recent AWS linux ami V2
# for private instances, we need to create 3 privatelink endpoints to enable Session Manager
# com.amazonaws.us-west-2.ssm
# com.amazonaws.us-west-2.ssmmessages
# com.amazonaws.us-west-2.ec2messages
# AND obviously, the subnet must be associated with a PRIVATE RT
# with obvious consideration for REGIONS instead of default "us-west-2"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Naming Conventions
        Parameters:
          - MyAccountName
          - MyVPCName
      - Label:
          default: CIDR range assignment to the VPC
        Parameters:
          - MyCidrBlock
          - MyEnableDnsHostnames 
          - MyEnableDnsSupport
    ParameterLabels:
      MyAccountName:
        default: The name of the AWS Account being used
      MyVPCName:
        default: What is the name you would like to assign to the VPC you are creating?

Parameters:
  MyAccountName:
    Description: Please enter the name of the AWS Account
    Type: String
  MyVPCName:
    Description: Please enter the name of this MyPrivateVPC
    Type: String
    Default: MyCFNCreatedVPC
  MyCidrBlock:
    Description: VPC CIDR Block - Each Octat must be 255 or less, and the end cidr range < 25 ie, 100.254.0.0/20
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|1[0-9]|2[0-4]))$
  MyEnableDnsHostnames:
    Description:  Enable VPC DNS Hostname lookups
    AllowedValues:
    - true
    - false
    Type: String
    Default: true
  MyEnableDnsSupport:
    Description:  Enable VPC DNS Support 
    AllowedValues:
    - true
    - false
    Type: String
    Default: true
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

Resources:
  MyPrivateVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MyCidrBlock
      EnableDnsHostnames: !Ref MyEnableDnsHostnames
      EnableDnsSupport: !Ref MyEnableDnsSupport
      InstanceTenancy: default
      Tags: 
      - Key: "Region"
        Value: !Sub '${AWS::Region}'
      - Key:  "Account"
        Value: !Sub '${AWS::AccountId}'
      - Key:  Account Name
        Value:  !Ref MyAccountName
      - Key: Name
        Value: !Sub '${MyVPCName}_vpc'
      - Key:  Resource
        Value: VPC

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
      - 0 
      - Fn::GetAZs: !Ref 'AWS::Region'
      CidrBlock: !Select 
      - 0
      -  Fn::Cidr: [ !Ref MyCidrBlock, 4, 8 ]
      MapPublicIpOnLaunch: false
      VpcId: !Ref MyPrivateVPC
      Tags: 
      - Key: "Region"
        Value: !Sub '${AWS::Region}'
      - Key:  "Account"
        Value: !Sub '${AWS::AccountId}'
      - Key:  Account Name
        Value:  !Ref MyAccountName
      - Key: Name
        Value: !Sub '${MyVPCName}_vpc'
      - Key:  Resource
        Value: Private Subnet

  MyAWSLinuxAmi2:
    Type:  AWS::EC2::Instance
    Properties: 
      SubnetId:  !Ref MySubnet
      AvailabilityZone: !Select 
      - 0 
      - Fn::GetAZs: !Ref 'AWS::Region' 
      ImageId:  !Ref LatestAmiId
      InstanceType: t3.micro
      IamInstanceProfile: !ImportValue InstanceProfileName
      SecurityGroupIds:  
      - Fn::GetAtt: MyEC2SecurityGroup.GroupId
      Tags:
      - Key: Name
        Value: !Sub 'TestInstance-${MyVPCName}_ami2'

# i need to attach the appropriate security group to my EC2 instance
  MyEC2SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription:  Private access to a test EC2 AWS-Linux AMI v2
        VpcId: !Ref MyPrivateVPC
        GroupName: !Sub 'TestInstanceSecurityGroup-${MyVPCName}'
        Tags:
        - Key: Name
          Value: !Sub 'TestInstanceSecurityGroup-${MyVPCName}_sg'

  MyEC2SecurityGroupIngress1:
    Type:  AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:  !Ref MyEC2SecurityGroup
      IpProtocol: all
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:  !Ref MyEC2SecurityGroup

  MyEC2SecurityGroupIngress2:
    Type:  AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:  !Ref MyEC2SecurityGroup
      IpProtocol: all
      FromPort: 0
      ToPort: 65535
      CidrIp: 0.0.0.0/0

  MyEC2SecurityGroupEgress:
    Type:  AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:  !Ref MyEC2SecurityGroup
      IpProtocol: '-1'
      FromPort: 0
      ToPort:   65535
      CidrIp: 0.0.0.0/0

  PrivateSSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      SecurityGroupIds: 
      - !Ref MyEC2SecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssm'
      SubnetIds: 
      - !Ref MySubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId: !Ref MyPrivateVPC

  PrivateSSMMessagesEndpoint:
    Type:  AWS::EC2::VPCEndpoint
    Properties: 
      SecurityGroupIds: 
      - !Ref MyEC2SecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ssmmessages'
      SubnetIds: 
      - !Ref MySubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId:  !Ref MyPrivateVPC

  PrivateEC2MessagesEndpoint:
    Type:  AWS::EC2::VPCEndpoint
    Properties: 
      SecurityGroupIds: 
      - !Ref MyEC2SecurityGroup
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ec2messages'
      SubnetIds: 
      - !Ref MySubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId: !Ref MyPrivateVPC

Outputs:
  MyVpcId:
    Description: The ID of the VPC
    Value: !Ref MyPrivateVPC
    Export:
      Name: !Sub "${AWS::StackName}-vpcid"
  MySubnetId:
    Description: The ID of the subnet
    Value: !Ref MySubnet
    Export:
      Name: !Sub "${AWS::StackName}-SubnetID"
  MyEC2Instance:
   Description:  My instance ID
   Value:  !Ref MyAWSLinuxAmi2