AWSTemplateFormatVersion: 2010-09-09
Description: VPC creation only - the simplest possible vpc config (with CIDR, IGW, route tables & Name parameters, of course )

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC Naming Conventions
        Parameters:
          - MyAccountName
          - MyVPCName
      - Label:
          default: CIDR range assignment to the VPC
        Parameters:
          - MyCidrBlock
    ParameterLabels:
      MyAccountName:
        default: The name of the AWS Account being used
      MyVPCName:
        default: What is the name you would like to assign to the VPC you are creating?

Parameters:
  MyAccountName:
    Description: Please enter the name of the AWS Account
    Type: String
  MyVPCName:
    Description: Please enter the name of this MyVPC
    Type: String
    Default: MyCFNCreatedVPC
  MyCidrBlock:
    Description: VPC CIDR Block - Each Octat must be 255 or less, and the end cidr range < 25 ie, 100.254.0.0/20
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|1[0-9]|2[0-4]))$

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref MyCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
      - Key: "Region"
        Value: !Sub '${AWS::Region}'
      - Key:  "Account"
        Value: !Sub '${AWS::AccountId}'
      - Key:  Account Name
        Value:  !Ref MyAccountName
      - Key: Name
        Value: !Sub '${MyVPCName}_vpc'
      - Key:  Resource
        Value: VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
      - Key: "Region"
        Value: !Sub '${AWS::Region}'
      - Key:  "Account"
        Value: !Sub '${AWS::AccountId}'
      - Key:  Account Name
        Value:  !Ref MyAccountName
      - Key: Name
        Value: !Sub '${MyVPCName}_igw'
      - Key:  Resource
        Value: Internet Gateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: MyVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVPC
      Tags: 
      - Key: "Region"
        Value: !Sub '${AWS::Region}'
      - Key:  "Account"
        Value: !Sub '${AWS::AccountId}'
      - Key:  Account Name
        Value:  !Ref MyAccountName
      - Key: Name
        Value: !Sub 'public_${MyVPCName}_rt'
      - Key:  Resource
        Value:  Public Route Table 

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTable