AWSTemplateFormatVersion: 2010-09-09
Description: Create Transit Gateway Attachments

# VPC id's
Region is assumed at runtime
routing considerations?  Hard coded?
Attach to an existing Transit Gateway?

Parameter:
  
Resources:
 
  MyTransitGatewayAttachment:
   Type: "AWS::EC2::TransitGatewayAttachment"
   Properties:
     Tags: 
     - Key: "Region"
       Value: !Sub '${AWS::Region}'
     - Key:  "Account"
       Value: !Sub '${AWS::AccountId}'
     - Key: "Product"
       Value: !Ref Product
     - Key: Resource
       Value: !Sub '${TagName}_vpctgwa'
     TransitGatewayId: !Ref MyTransitGateWay
     VPCId: !Ref VPCId