AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation VPC template
# Appropriate Tags
# Account
# Account Name
# Resource
# Resource Name
# Product
# Organization
# Region

Parameters:
  MyOrganization:
    Description:  Please enter your organization number here
    Type:  String
    Default: o-default

  MyAccountName:
    Description: Please enter your target AWS Account Name
    Type: String
    Default:  MyDefaultAccountName

  VPCCidr:
    Description:  Please enter a VPC CIDR
    Type: 'List<AWS::EC2::VPC::Id>'

  MySubnetList:
    Description: Select the subnets to attach with the VPC to the Transit Gateway
    Type: List<AWS::EC2::Subnet::Id>
    VpcId: VPCCidr

  Product:
    Description:  Please enter the Product this is being built to support
    Type: String

  TagName:
    Description:  Please enter the resource name prefix here
    Type:  String
       
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
      - Key: "Region"
        Value: !Sub '${AWS::Region}'
      - Key:  "Account"
        Value: !Sub '${AWS::AccountId}'
        - Key:  Account Name
        Value:  !Ref myAccountName
      - Key: "Product"
        Value: !Ref Product
      - Key: Name
        Value: !Sub '${AccountName}${AWS::Region}TGW_vpc'
      - Key:  Resource
        Value: VPC
      - Key: Organization
        Value: !Ref MyOrganization