AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template primitive which creates a Microsoft AD Directory Service.
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: Directory Service Configuration
        Parameters: 
          - VpcId
          - Name
          - ShortName
          - Edition
          - SecretName
          - MsAdAdminPasswordLength
          - SubnetId1
          - SubnetId2
      - Label:
          default: Environment and Tags
        Parameters:
          - EnvironmentId
          - Contact
          - ProjectId
          - ProjectData
Parameters:
  VpcId:
    Description: Deploy to which VPC
    Type: AWS::EC2::VPC::Id
  Name:
    Type: String
    Default: DNSName
  ShortName:
    Type: String
    Default: ShortName
  Edition:
    Type: String
    Default: Standard
    AllowedValues:
      - Standard
      - Enterprise
  SecretName:
    Type: String
    Default: SecretName
  MsAdAdminPasswordLength:
    Type: Number
    Default: 8
  SubnetId1:
    Description: Subnet 1
    Type: AWS::EC2::Subnet::Id
  SubnetId2:
    Description: Subnet 2
    Type: AWS::EC2::Subnet::Id
  EnvironmentId:
    Type: String
    Default: dev
  Contact:
    Type: String
    Default: ContactName
  ProjectId:
    Type: String
    Default: ProjectId
  ProjectData:
    Type: String
    Default: env=DEV
Resources:
  MsAdSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "This is a Secrets Manager secret for an MS AD resource, containing the admin password necessary for the initial setup of MS AD"
      Name: !Ref SecretName
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: !Ref MsAdAdminPasswordLength
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: EnvironmentId
          Value: !Ref EnvironmentId
        - Key: Contact
          Value: !Ref Contact
        - Key: ProjectId
          Value: !Ref ProjectId
        - Key: ProjectData
          Value: !Ref ProjectData
  MyDirectory:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: !Ref Name
      ShortName: !Ref ShortName
      Password: !Join ['', ['{{resolve:secretsmanager:', !Ref MsAdSecret, ':SecretString:password}}' ]]
      Edition: !Ref Edition
      VpcSettings:
        SubnetIds:
          - !Ref SubnetId1
          - !Ref SubnetId2
        VpcId: !Ref VpcId
Outputs:
  MyDirectoryId:
    Description: The ID of the directory
    Value: !Ref MyDirectory
    Export:
      Name: !Sub ${AWS::StackName}-${ShortName}