AWSTemplateFormatVersion: '2010-09-09'

Description: AWS OpsWorks for Chef Automate - IAM Resource for nodes

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      Path: /
      Policies:
        - PolicyName: InstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - opsworks-cm:AssociateNode
                  - opsworks-cm:DescribeNodeAssociationStatus
                Effect: Allow
                Resource: '*'
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: InstanceRole
      
Outputs:
  InstanceRoleArn:
    Description: InstanceRoleArn
    Value: !GetAtt [InstanceRole, Arn]
  InstanceProfileArn:
    Description: InstanceProfileArn
    Value: !GetAtt [InstanceProfile, Arn]
