---
AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFormation template primitive which creates an S3 bucket resource.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Parameters
        Parameters:
          - BucketName
          - AccessControl
          - KmsMasterKeyId
          - SseAlgorithm
          - VersioningConfiguration
      - Label:
          default: Environment and Tags
        Parameters:
          - EnvironmentId
          - Contact
          - ProjectId
          - ProjectData

Parameters:
  EnvironmentId:
    Type: String
    Default: dev
  Contact:
    Type: String
    Default: Name
  ProjectId:
    Type: String
    Default: ProjectId
  ProjectData:
    Type: String
    Default: env=DEV
  AccessControl:
    Description: Canned ACL. Default is Private, and should not be changed unless you know exactly why you're changing it. See https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl
    AllowedValues:
      - AuthenticatedRead
      - AwsExecRead
      - BucketOwnerRead
      - BucketOwnerFullControl
      - LogDeliveryWrite
      - Private
      - PublicRead
      - PublicReadWrite
    Type: String
    Default: Private
  AccelerationStatus:
    Description: Sets S3 bucket acceleration status. Default should be Suspended. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-accelerateconfiguration.html
    AllowedValues:
      - Enabled
      - Suspended
    Type: String
    Default: Suspended
  BucketName:
    Description: Sets S3 bucket name. If left blank, name will be autogenerated. Default is blank.
    Type: String
  KmsMasterKeyId:
    Description: Leave blank unless SseAlgorithm is set to aws:kms *and* you want to use your own custom key.
    Type: String
  SseAlgorithm:
    Description: Default S3 encryption algorithm to use. Leave at the default value of AES256 unless you want to incur KMS charges.
    AllowedValues:
      - AES256
      - aws:kms
    Type: String
    Default: AES256
  VersioningConfiguration:
    Description: Sets S3 bucket versioning. Default is Enabled. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfig.html
    AllowedValues:
      - Enabled
      - Suspended
    Type: String
    Default: Enabled

Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, ""]]
  HasKmsMasterKeyId: !Not [!Equals [!Ref KmsMasterKeyId, ""]]

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: !Ref AccessControl
      AccelerateConfiguration:
        AccelerationStatus: !Ref AccelerationStatus
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !If [HasKmsMasterKeyId, !Ref KmsMasterKeyId, !Ref "AWS::NoValue"]
              SSEAlgorithm: !Ref SseAlgorithm
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref "AWS::NoValue"]
      Tags:
        - Key: EnvironmentId
          Value: !Ref EnvironmentId
        - Key: Contact
          Value: !Ref Contact
        - Key: ProjectId
          Value: !Ref ProjectId
        - Key: ProjectData
          Value: !Ref ProjectData
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
    DeletionPolicy: Delete

Outputs:
  BucketName:
    Value: !Ref 'MyBucket'
    Description: Name of the Amazon S3 bucket.
